### ISSUE TITLE
golangci-lint is not reporting issues that golint catches

### ISSUE THREAD

**Issue by atc0005** [atc0005/todo#29]
See also https://github.com/atc0005/todo/issues/9#issuecomment-620505235

While working on another project, I used a VSCode instance within a VM that did not have golangci-lint installed, and so defaulted to using `golint` for linting. It caught these issues that golangci-lint didn't report:

```
$ golint ./... | grep -v vendor
cmd/pkg1/constants.go:19:7: exported const MB should have comment or be unexported
cmd/pkg2/main.go:38:6: exported type AppConfig should have comment or be unexported
cmd/pkg3/main.go:32:6: exported type Results should have comment or be unexported
events/validate.go:24:1: exported function ValidatePayload should have comment or be unexported
```

I substituted the real package names with placeholders, but the rest is untouched.

Here is the entries in the `.golangci.yml` file:

```yaml
linters:
  enable:
    - dogsled
    - goimports
    - gosec
    - stylecheck
    - goconst
    - depguard
    - prealloc
    - misspell
    - maligned
    - dupl
    - unconvert
    - gofmt
    - golint
    - gocritic
    - scopelint
```

This is with golangci-lint v1.28.3.
